### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by yuchi** [michael/hub#20] opened 2013-02-01 09:48 UTC
@michael the first who want to tackle this will auto-assign to himself the issue.

**Comment by michael** [comment] 2013-02-01 11:46
Assigned this to the next milestone 0.2.0.

@yuchi did you have a chance to look into #10? would be nice to have this solved as we'll do the release this afternoon. Oh and Oliver confirmed that yesterday the build did not work due to an outage of the boost-svn server.

**Comment by yuchi** [comment] 2013-02-01 11:52
About #10: as soon as I reach lunch I solve it, it's in my "urgencies" part of brain.

About swig-v8: cool, I'll try again.

**Closed as completed** 2014-10-06 21:42 UTC
Labels: enhancement
